# Generated by Django 4.0.3 on 2022-04-12 12:27

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Employee status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Manager status'),
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=128, null=True)),
                ('brith_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('City', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('upload', models.ImageField(blank=True, height_field=40, null=True, upload_to=accounts.models.CustomUserProfile.user_directory_path, width_field=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
