# Generated by Django 4.0.3 on 2022-04-13 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('consumed_time', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestChangeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_time', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('1', 'Waiting'), ('2', 'Accepted'), ('3', 'Denied')], default='1', max_length=1)),
                ('requested_by', models.ForeignKey(null=True, on_delete=models.SET('Former employee'), related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('review_by', models.ForeignKey(null=True, on_delete=models.SET('Former manager'), related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
