# Generated by Django 4.0.3 on 2022-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_name_task_title_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchangetask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestchangetask',
            name='description_of_change',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requestchangetask',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
