# Generated by Django 4.0.4 on 2022-05-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_id_customer_task_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestchangetask',
            old_name='task_id',
            new_name='task',
        ),
    ]
