# Generated by Django 4.0.3 on 2022-04-19 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_requestchangetask_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('Former employee'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
