# Generated by Django 4.0.4 on 2022-04-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('id_discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.discount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('id_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task')),
            ],
        ),
    ]
