# Generated by Django 4.0.4 on 2022-04-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_created_date_task_date_modified_and_more'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='id_task',
            field=models.ManyToManyField(limit_choices_to={'invoiced': False, 'is_active': False}, to='task.task'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='CustomerTask',
        ),
    ]
