# Generated by Django 4.0.4 on 2022-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='id_task',
            field=models.ManyToManyField(limit_choices_to={'invoiced': False, 'is_active': False}, to='task.task'),
        ),
    ]
