# Generated by Django 4.0.4 on 2022-04-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_name_task_title_requestchangetask_description_and_more'),
        ('invoice', '0002_invoice_id_task_alter_invoice_id_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id_discount',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_task',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
