# Generated by Django 4.0.4 on 2022-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_name_task_title_requestchangetask_description_and_more'),
        ('invoice', '0003_alter_invoice_id_discount_alter_invoice_id_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id_task',
            field=models.ManyToManyField(limit_choices_to={'invoiced': False, 'is_active': False}, to='task.task'),
        ),
    ]
